parameters:
    nadia.menu.cache_tag_aware_adapter.known_tag_versions_ttl: 0.15

services:
    nadia.menu.cache_tag_aware_adapter:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        arguments:
            - '@cache.adapter.array'
            - '@cache.adapter.array'
            - '%nadia.menu.cache_tag_aware_adapter.known_tag_versions_ttl%'

    Nadia\Bundle\NadiaMenuBundle\MenuProvider\MenuProvider:
        class: Nadia\Bundle\NadiaMenuBundle\MenuProvider\MenuProvider
        arguments:
            # Parameter "nadia.menu.static_menu_cache_dir" is defined in NadiaMenuExtension
            - '%nadia.menu.static_menu_cache_dir%'
            - []
            - []

    # MenuFactory for KnpMenu
    Nadia\Bundle\NadiaMenuBundle\MenuFactory\KnpMenuFactory:
        arguments:
            - '@Nadia\Bundle\NadiaMenuBundle\MenuProvider\MenuProvider'
            - '@knp_menu.factory'
            - '@nadia.menu.cache_tag_aware_adapter'
            - '@security.token_storage'
            - '@security.authorization_checker'
